export const themes = {
  'Midnight Black': {
    name: 'Midnight Black',
    bg: 'bg-[#0e0e0d]',
    bgSecondary: 'bg-[#161513]',
    cardBg: 'bg-[#161513]/90 border-white/5',
    cardBgOpaque: 'bg-[#161513] border-white/5',
    sidebarBg: 'bg-[#0a0a09] border-white/5',
    border: 'border-white/5',
    borderStrong: 'border-white/10',
    text: 'text-[#e5e2e1]',
    textMuted: 'text-[#c5b9a5]',
    textMutedLight: 'text-[#a69984]',
    textMutedDark: 'text-[#887e6d]',
    accent: 'text-[#ffc53d]',
    accentBg: 'bg-[#ffc53d]',
    accentHoverBg: 'hover:bg-[#ffb014]',
    accentText: 'text-[#2c1a00]',
    accentLight: 'text-[#ffe2ab]',
    accentLightBg: 'bg-[#ffe2ab]/10',
    accentLightBorder: 'border-[#ffe2ab]/20',
    cardHover: 'hover:bg-white/[0.01]',
    inputBg: 'bg-[#0e0e0d]',
    inputBorder: 'border-white/10',
    buttonOutline: 'border-white/10 hover:border-white/20 text-white',
    divider: 'divide-white/5',
    tagAdmin: 'bg-white/5 border border-white/10 text-[#a69984]/50',
    tagManager: 'bg-[#ffe2ab]/10 border border-[#ffe2ab]/20 text-[#ffe2ab]',
    tagStaff: 'bg-sky-500/10 border border-sky-500/20 text-sky-400',
    tagActive: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400',
    tagSuspended: 'bg-rose-500/10 border border-rose-500/20 text-rose-400',
    tagTrial: 'bg-amber-500/10 border border-amber-500/20 text-amber-400',
    tagExpired: 'bg-white/5 border border-white/10 text-[#a69984]/50',
    scrollbarThumb: 'scrollbar-thumb-white/10'
  },
  'Pristine White': {
    name: 'Pristine White',
    bg: 'bg-[#f4f3f0]',
    bgSecondary: 'bg-[#ffffff]',
    cardBg: 'bg-white/95 border-[#ede6da] shadow-[0_4px_16px_rgba(142,130,111,0.04)]',
    cardBgOpaque: 'bg-white border-[#ede6da] shadow-[0_4px_16px_rgba(142,130,111,0.04)]',
    sidebarBg: 'bg-[#edeae5] border-[#dfdad0]',
    border: 'border-[#ede6da]',
    borderStrong: 'border-[#cdc7bc]',
    text: 'text-[#1a1917]',
    textMuted: 'text-[#4c4a45]',
    textMutedLight: 'text-[#68655e]',
    textMutedDark: 'text-[#7e7a72]',
    accent: 'text-[#cfa426]',
    accentBg: 'bg-[#cfa426]',
    accentHoverBg: 'hover:bg-[#b08b1f]',
    accentText: 'text-white',
    accentLight: 'text-[#8c6f17]',
    accentLightBg: 'bg-[#cfa426]/10',
    accentLightBorder: 'border-[#cfa426]/20',
    cardHover: 'hover:bg-black/[0.01]',
    inputBg: 'bg-[#fafaf9]',
    inputBorder: 'border-[#e2ddd5]',
    buttonOutline: 'border-[#cdc7bc] hover:border-[#b0a99c] text-[#1a1917]',
    divider: 'divide-[#e2ddd5]',
    tagAdmin: 'bg-[#6e6b63]/5 border border-[#6e6b63]/15 text-[#6e6b63]',
    tagManager: 'bg-[#cfa426]/10 border border-[#cfa426]/20 text-[#8c6f17]',
    tagStaff: 'bg-sky-600/10 border border-sky-600/20 text-sky-700',
    tagActive: 'bg-emerald-600/10 border border-emerald-600/20 text-emerald-700',
    tagSuspended: 'bg-rose-600/10 border border-rose-600/20 text-rose-700',
    tagTrial: 'bg-amber-600/10 border border-amber-600/20 text-amber-700',
    tagExpired: 'bg-[#edeae5]/5 border border-[#edeae5]/15 text-[#6e6b63]',
    scrollbarThumb: 'scrollbar-thumb-black/10'
  },
  'Delicious Red': {
    name: 'Delicious Red',
    bg: 'bg-[#faf9f6]',
    bgSecondary: 'bg-[#ffffff]',
    cardBg: 'bg-white/95 border-[#ede6da] shadow-[0_4px_20px_rgba(200,16,46,0.03)]',
    cardBgOpaque: 'bg-white border-[#ede6da] shadow-[0_4px_20px_rgba(200,16,46,0.03)]',
    sidebarBg: 'bg-[#f5f2eb] border-[#e8e2d5]',
    border: 'border-[#ede6da]',
    borderStrong: 'border-[#d4c3b3]',
    text: 'text-[#1a1917]',
    textMuted: 'text-[#5c564c]',
    textMutedLight: 'text-[#787165]',
    textMutedDark: 'text-[#928b7e]',
    accent: 'text-[#c8102e]',
    accentBg: 'bg-[#c8102e]',
    accentHoverBg: 'hover:bg-[#a00c22]',
    accentText: 'text-white',
    accentLight: 'text-[#900c1e]',
    accentLightBg: 'bg-[#c8102e]/8',
    accentLightBorder: 'border-[#c8102e]/15',
    cardHover: 'hover:bg-black/[0.005]',
    inputBg: 'bg-[#fcfbfa]',
    inputBorder: 'border-[#e1dad0]',
    buttonOutline: 'border-[#dcd4c8] hover:border-[#bdae9c] text-[#1a1917]',
    divider: 'divide-[#ede6da]',
    tagAdmin: 'bg-[#5c564c]/8 border border-[#5c564c]/15 text-[#5c564c]',
    tagManager: 'bg-[#c8102e]/10 border border-[#c8102e]/20 text-[#c8102e]',
    tagStaff: 'bg-sky-600/10 border border-sky-600/20 text-sky-700',
    tagActive: 'bg-emerald-600/10 border border-emerald-600/20 text-emerald-700',
    tagSuspended: 'bg-rose-600/10 border border-rose-600/20 text-rose-700',
    tagTrial: 'bg-amber-600/10 border border-amber-600/20 text-amber-700',
    tagExpired: 'bg-[#5c564c]/8 border border-[#5c564c]/15 text-[#5c564c]',
    scrollbarThumb: 'scrollbar-thumb-black/10'
  },
  'Bordeaux Reserve': {
    name: 'Bordeaux Reserve',
    bg: 'bg-[#180a0c]',
    bgSecondary: 'bg-[#221013]',
    cardBg: 'bg-[#221013]/90 border-[#4a1c24]',
    cardBgOpaque: 'bg-[#221013] border-[#4a1c24]',
    sidebarBg: 'bg-[#100305] border-[#4a1c24]',
    border: 'border-[#4a1c24]',
    borderStrong: 'border-[#6b2c37]',
    text: 'text-[#f5ecea]',
    textMuted: 'text-[#d8b8b5]',
    textMutedLight: 'text-[#c29c98]',
    textMutedDark: 'text-[#a87e79]',
    accent: 'text-[#f5aca4]',
    accentBg: 'bg-[#f5aca4]',
    accentHoverBg: 'hover:bg-[#e0928b]',
    accentText: 'text-[#380d12]',
    accentLight: 'text-[#fad2ce]',
    accentLightBg: 'bg-[#f5aca4]/15',
    accentLightBorder: 'border-[#f5aca4]/30',
    cardHover: 'hover:bg-white/[0.01]',
    inputBg: 'bg-[#160608]',
    inputBorder: 'border-[#4a1c24]',
    buttonOutline: 'border-[#6b2c37] hover:border-[#8c3d4b] text-[#f5ecea]',
    divider: 'divide-[#4a1c24]',
    tagAdmin: 'bg-white/5 border border-white/10 text-[#d8b8b5]/50',
    tagManager: 'bg-[#f5aca4]/10 border border-[#f5aca4]/20 text-[#f5aca4]',
    tagStaff: 'bg-[#ffc53d]/10 border border-[#ffc53d]/20 text-[#ffe2ab]',
    tagActive: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400',
    tagSuspended: 'bg-rose-500/10 border border-rose-500/20 text-rose-400',
    tagTrial: 'bg-amber-500/10 border border-amber-500/20 text-amber-400',
    tagExpired: 'bg-white/5 border border-white/10 text-[#d8b8b5]/50',
    scrollbarThumb: 'scrollbar-thumb-white/10'
  },
  'Deep Teal': {
    name: 'Deep Teal',
    bg: 'bg-[#051112]',
    bgSecondary: 'bg-[#0c1c1e]',
    cardBg: 'bg-[#0c1c1e]/90 border-[#1a383b]',
    cardBgOpaque: 'bg-[#0c1c1e] border-[#1a383b]',
    sidebarBg: 'bg-[#02090a] border-[#1a383b]',
    border: 'border-[#1a383b]',
    borderStrong: 'border-[#285357]',
    text: 'text-[#dcf0f2]',
    textMuted: 'text-[#b0cdcf]',
    textMutedLight: 'text-[#95b4b7]',
    textMutedDark: 'text-[#7ca1a3]',
    accent: 'text-[#48e5ec]',
    accentBg: 'bg-[#48e5ec]',
    accentHoverBg: 'hover:bg-[#34c9cf]',
    accentText: 'text-[#032426]',
    accentLight: 'text-[#9ef7fa]',
    accentLightBg: 'bg-[#48e5ec]/15',
    accentLightBorder: 'border-[#48e5ec]/30',
    cardHover: 'hover:bg-white/[0.01]',
    inputBg: 'bg-[#030d0e]',
    inputBorder: 'border-[#1a383b]',
    buttonOutline: 'border-[#285357] hover:border-[#387277] text-[#dcf0f2]',
    divider: 'divide-[#1a383b]',
    tagAdmin: 'bg-white/5 border border-white/10 text-[#b0cdcf]/50',
    tagManager: 'bg-[#48e5ec]/10 border border-[#48e5ec]/20 text-[#48e5ec]',
    tagStaff: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400',
    tagActive: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400',
    tagSuspended: 'bg-rose-500/10 border border-rose-500/20 text-rose-400',
    tagTrial: 'bg-amber-500/10 border border-amber-500/20 text-amber-400',
    tagExpired: 'bg-white/5 border border-white/10 text-[#b0cdcf]/50',
    scrollbarThumb: 'scrollbar-thumb-white/10'
  },
  'Custom Palette': {
    name: 'Custom Palette',
    bg: 'bg-[var(--custom-bg)]',
    bgSecondary: 'bg-[var(--custom-card-bg)]',
    cardBg: 'bg-[var(--custom-card-bg)]/90 border-[var(--custom-accent)]/10',
    cardBgOpaque: 'bg-[var(--custom-card-bg)] border-[var(--custom-accent)]/10',
    sidebarBg: 'bg-[var(--custom-bg)] border-[var(--custom-accent)]/10',
    border: 'border-[var(--custom-accent)]/5',
    borderStrong: 'border-[var(--custom-accent)]/15',
    text: 'text-[var(--custom-text)]',
    textMuted: 'text-[var(--custom-text-muted)]',
    textMutedLight: 'text-[var(--custom-text-muted)]/80',
    textMutedDark: 'text-[var(--custom-text-muted)]/60',
    accent: 'text-[var(--custom-accent)]',
    accentBg: 'bg-[var(--custom-accent)]',
    accentHoverBg: 'hover:opacity-90',
    accentText: 'text-black',
    accentLight: 'text-[var(--custom-accent)]',
    accentLightBg: 'bg-[var(--custom-accent)]/15',
    accentLightBorder: 'border-[var(--custom-accent)]/20',
    cardHover: 'hover:bg-white/[0.01]',
    inputBg: 'bg-[var(--custom-bg)]',
    inputBorder: 'border-[var(--custom-accent)]/20',
    buttonOutline: 'border-[var(--custom-accent)]/20 text-[var(--custom-text)]',
    divider: 'divide-[var(--custom-accent)]/10',
    tagAdmin: 'bg-white/5 border border-white/10 text-[var(--custom-text-muted)]/60',
    tagManager: 'bg-[var(--custom-accent)]/10 border border-[var(--custom-accent)]/20 text-[var(--custom-accent)]',
    tagStaff: 'bg-sky-500/10 border border-sky-500/20 text-sky-400',
    tagActive: 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-400',
    tagSuspended: 'bg-rose-500/10 border border-rose-500/20 text-rose-400',
    tagTrial: 'bg-amber-500/10 border border-amber-500/20 text-amber-400',
    tagExpired: 'bg-white/5 border border-white/10 text-[var(--custom-text-muted)]/60',
    scrollbarThumb: 'scrollbar-thumb-white/10'
  }
};

export const translations: Record<string, Record<string, string>> = {
  en: {
    adminConsole: "Admin Console",
    general: "General Settings",
    payments: "Payments & Billing",
    hardware: "Hardware Connection",
    staff: "Staff Management",
    security: "Security Controls",
    menu: "Food Menu Editor",
    analytics: "Business Analytics",
    activityLog: "Activity Log",
    menuEditor: "Food Menu Editor",
    saveChanges: "Save Changes",
    signOut: "Sign Out",
    searchPlaceholder: "Search parameters...",
    administrator: "Administrator",
    generalTitle: "General Settings",
    generalDesc: "Configure basic information, customize receipt design templates, and select layout color themes.",
    restaurantInfo: "Restaurant Information",
    restaurantName: "Restaurant Name",
    contactEmail: "Primary Contact Email",
    taxIdLabel: "Tax Identifier / VAT Number",
    businessAddress: "Physical Address",
    saveProfile: "Save Profile",
    globalThemeTitle: "Global Aesthetic Theme",
    customThemeConfig: "Custom Theme Configuration",
    customThemeDesc: "Design your own bespoke dashboard aesthetic",
    diningModes: "Dining Modes",
    diningModesDesc: "Enable or disable dining options available to customers in the digital menu and cashier terminals.",
    displayCurrency: "Display Currency",
    taxRatesByDining: "Tax Rates by Dining Option",
    receiptOptionsTitle: "Invoice & Receipt Layout Options",
    showLogo: "Show Restaurant Logo",
    showLogoDesc: "Include brand logo mark",
    showTaxId: "Show Tax ID / VAT Number",
    showTaxIdDesc: "Include legal tax identifiers",
    showServer: "Show Server Name",
    showServerDesc: "Print name of assigned cashier",
    showTable: "Show Table Number",
    showTableDesc: "Display dining table IDs",
    showTimestamp: "Show Order Timestamp",
    showTimestampDesc: "Include date/time details",
    showFeedbackQr: "Show Feedback QR Code",
    showFeedbackQrDesc: "Link customers to web review",
    showSocial: "Show Social Handles",
    showSocialDesc: "Display digital links",
    includeServiceCharge: "Include Service Charge",
    includeServiceChargeDesc: "Add auto 10% gratuity line",
    showCustomFooter: "Show Custom Footer Message",
    showCustomFooterDesc: "Append custom text to ticket bottom",
    livePreview: "Live Preview",
    realtimeSync: "Real-time Sync",
    currentTable: "TABLE: T-14",
    serverLabel: "SERVER: JULIAN B.",
    orderLabel: "Order #2345",
    subtotal: "Subtotal",
    tax: "Tax",
    serviceCharge: "Service Charge (10%)",
    gratuity: "Gratuity (Suggested 20%)",
    grandTotal: "Grand Total",
    regionalSettings: "Regional & Currency Settings",
    languageSelect: "Dashboard Language",
    langEn: "English (US)",
    langJa: "日本語 (Japanese)",
    langZh: "中文（简体）",
    langKo: "한국어 (Korean)",
    digitalMenuPrefs: "Digital Menu Preferences & Exclusions",
    maxDisplayPrice: "Maximum Display Price",
    maxDisplayPriceDesc: "Items priced above this amount will be hidden from the customer-facing menu.",
    excludedFoodTags: "Excluded Food Tags",
    excludedFoodTagsDesc: "Hide menu items tagged with these categories (e.g. GF, Veg, Non-Veg, Seafood).",
    digitalMenuFeatures: "Digital Menu Features",
    enableAIConcierge: "Enable AI Concierge",
    enableAIConciergeDesc: "Allow customers to ask the AI concierge about menu recommendations and pairings.",
    enableSelfCheckout: "Enable Customer Self-Checkout",
    enableSelfCheckoutDesc: "Permit customers to place orders directly from their tables using self-checkout.",
    subAndBilling: "Subscription & Billing",
    subDesc: "Manage your enterprise plan, payment methods, and review upcoming invoices for seamless operations.",
    downloadStatements: "Download Statements",
    currentPlan: "Current Plan",
    planName: "Enterprise Growth",
    planBilling: "Billed Annually • Renews on Nov 15, 2026",
    activeTerminals: "Active Terminals",
    cloudStorage: "Cloud Storage",
    changePlan: "Change Plan",
    manageAddons: "Manage Addons",
    paymentMethod: "Payment Method",
    editBtn: "Edit",
    defaultMethod: "Default",
    addBackupMethod: "Add Backup Method",
    invoiceLedger: "Upcoming & Recent Invoices",
    dateCol: "Date",
    descCol: "Description",
    amountCol: "Amount",
    statusCol: "Status",
    actionCol: "Action",
    upcomingStatus: "Upcoming",
    paidStatus: "Paid",
    failedStatus: "Failed",
    menuWelcome: "Food Menu Editor",
    menuDesc: "Create, edit, categorize, and manage your restaurant's digital menu items and special recommendations.",
    avgProfit: "AVG. PROFIT MARGIN",
    totalItems: "TOTAL MENU ITEMS",
    specDishes: "SPECIAL DISHES",
    manageCats: "Manage Categories",
    addMenuItem: "Add Menu Item",
    editMenuItem: "Edit Menu Item",
    itemCol: "ITEM",
    categoryCol: "CATEGORY",
    costCol: "COST",
    priceCol: "PRICE",
    marginCol: "MARGIN",
    actionsCol: "ACTIONS",
    categoryManager: "Category Manager",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    categoryIcon: "Category Icon",
    activeCategories: "Active Categories",
    hardwareFleet: "Hardware Fleet",
    hardwareDesc: "Monitor your connected terminal fleet, printers, Expo screens, and open/test cash drawer integrations.",
    pairNewDevice: "Pair New Device",
    globalPreferences: "Global Preferences",
    autoReconnect: "Auto-Reconnect Devices",
    defaultGateway: "Default Network Gateway",
    btDiscovery: "Bluetooth Beacon Discovery",
    statusIndicators: "Active Status Alerts",
    testDrawerKick: "Test Drawer Kick",
    cashDrawers: "Cash Drawers",
    openOnCash: "Open automatically on Cash checkout",
    requireManager: "Require manager authorization code (PIN) for manual opening",
    staffDirectory: "Staff Directory",
    staffDesc: "Monitor employee statuses, track roster shifts, and review customer satisfaction ratings.",
    onShift: "ON SHIFT",
    offDuty: "OFF DUTY",
    overtime: "OVERTIME",
    weeklyRoster: "Weekly Shift Roster",
    securityConsole: "Security Console",
    securityDesc: "Modify role access controls, review system audit records, and set session timeout configurations.",
    timeoutLabel: "Session Idle Timeout (Minutes)",
    passcodeLabel: "Default Staff Passcode Length (Digits)",
    roleAccess: "Role Access Privileges",
    auditTrail: "System Audit Trail",
    taxBasisLabel: "Tax Calculation Basis",
    preTaxLabel: "Pre-tax (Exclusive)",
    postTaxLabel: "Post-tax (Inclusive)",
    taxBasisDesc: "Choose whether tax is calculated on top of subtotal (Pre-tax) or included in pricing (Post-tax).",
    subtotalInclusive: "Subtotal (Tax Incl.)",
    includedTax: "Included Tax (8%)",
    analyticsTitle: "Business Analytics",
    analyticsDesc: "Revenue, orders, staff performance and menu insights for your establishment.",
    analyticsRange: "Date Range",
    analyticsToday: "Today",
    analyticsWeek: "This Week",
    analyticsMonth: "This Month",
    analytics30: "Last 30 Days",
    analyticsRevenue: "Gross Revenue",
    analyticsOrders: "Total Orders",
    analyticsAvgCheck: "Avg. Check",
    analyticsCovers: "Covers Served",
    analyticsRevTrend: "Revenue Trend",
    analyticsOrderTypes: "Orders by Type",
    analyticsPeakHours: "Peak Hour Distribution",
    analyticsTopItems: "Top Menu Items by Revenue",
    analyticsStaffPerf: "Staff Performance",
    analyticsPayMethods: "Payment Method Breakdown",
    analyticsDineIn: "Dine-in",
    analyticsTakeaway: "Takeaway",
    analyticsDelivery: "Delivery",
    analyticsExport: "Export Report",
    timeBasedMenu: "Time-Based Menu Schedule",
    timeBasedMenuDesc: "Enable lunch and dinner menu service windows. When enabled, customer digital menu filters menu items dynamically according to the current local time.",
    lunchMenuTime: "Lunch Service Hours",
    dinnerMenuTime: "Dinner Service Hours",
    mealPeriodLabel: "Meal Period",
    lunchOnly: "Lunch Only",
    dinnerOnly: "Dinner Only",
    bothMeals: "Both (All Day)",
    timeBasedMenuInfoNote: "Items not assigned to a specific period (All Day) will appear during all service windows.",
    timeBasedMenuDisabledNote: "Note: When Time-Based Menu is disabled, all menu items are visible all day regardless of their meal period assignment.",
    inventory: "Inventory",
    inventoryTitle: "Inventory & Recipes",
    inventoryDesc: "Configure ingredients, link menu items to recipes for auto-deductions, manage suppliers, purchase orders, and track waste logs.",
  },
  ja: {
    adminConsole: "管理コンソール",
    general: "一般設定",
    payments: "売上・請求",
    hardware: "周辺機器設定",
    staff: "従業員管理",
    security: "セキュリティ",
    menu: "メニュー編集",
    analytics: "ビジネス分析",
    activityLog: "操作履歴",
    menuEditor: "メニュー編集",
    saveChanges: "設定を保存",
    signOut: "サインアウト",
    searchPlaceholder: "パラメータを検索...",
    administrator: "管理者",
    generalTitle: "一般設定",
    generalDesc: "店舗の基本情報、レシート用デザインテンプレート、および画面表示テーマを設定します。",
    restaurantInfo: "店舗情報",
    restaurantName: "店舗名",
    contactEmail: "連絡先メールアドレス",
    taxIdLabel: "税金登録番号 / VAT",
    businessAddress: "店舗所在地",
    saveProfile: "店舗情報を保存",
    globalThemeTitle: "表示テーマ設定",
    customThemeConfig: "カスタムテーマ設定",
    customThemeDesc: "お好みのカラーでダッシュボードをカスタマイズします",
    diningModes: "service モード",
    diningModesDesc: "デジタルメニューとレジで利用可能なダイニングオプションを有効/無効にします。",
    displayCurrency: "表示通貨",
    taxRatesByDining: "ダイニングオプション別税率",
    receiptOptionsTitle: "レシート・請求書レイアウト設定",
    showLogo: "店舗ロゴを表示する",
    showLogoDesc: "レシート上部にロゴマークを印刷します",
    showTaxId: "税登録番号を表示する",
    showTaxIdDesc: "レシートに税登録番号（VAT）を含めます",
    showServer: "担当スタッフ名を表示する",
    showServerDesc: "レシートにレジ担当者名を印刷します",
    showTable: "テーブル番号を表示する",
    showTableDesc: "客席テーブルIDを表示します",
    showTimestamp: "注文日時を表示する",
    showTimestampDesc: "レシートに会計日時を含めます",
    showFeedbackQr: "評価用QRコードを表示する",
    showFeedbackQrDesc: "お客様評価ページへのQRコードを印刷します",
    showSocial: "SNSリンクを表示する",
    showSocialDesc: "公式SNSアカウントのリンクを表示します",
    includeServiceCharge: "サービス料を含める",
    includeServiceChargeDesc: "自動で10%のサービス料を加算します",
    showCustomFooter: "フッターメッセージを表示する",
    showCustomFooterDesc: "レシート下部に任意のテキストを追加します",
    livePreview: "リアルタイムプレビュー",
    realtimeSync: "同期中",
    currentTable: "テーブル: T-14",
    serverLabel: "担当: ジュリアン B.",
    orderLabel: "注文番号 #2345",
    subtotal: "小計",
    tax: "消費税",
    serviceCharge: "サービス料 (10%)",
    gratuity: "チップ (推奨20%)",
    grandTotal: "総合計",
    regionalSettings: "地域および通貨の設定",
    languageSelect: "表示言語",
    langEn: "English (US)",
    langJa: "日本語 (Japanese)",
    langZh: "中文（简体）",
    langKo: "한국어 (Korean)",
    digitalMenuPrefs: "デジタルメニューの表示・機能設定",
    maxDisplayPrice: "メニュー表示の最大価格",
    maxDisplayPriceDesc: "この設定金額を超えるメニュー項目は、顧客向けデジタルメニューには非表示になります。",
    excludedFoodTags: "非表示にするタグの選択",
    excludedFoodTagsDesc: "選択したタグが含まれるメニュー項目を顧客メニューから除外します。",
    digitalMenuFeatures: "デジタルメニュー of 機能制御",
    enableAIConcierge: "AIコンシェルジュ機能を有効にする",
    enableAIConciergeDesc: "お客様がメニューの推奨事項やペアリングについてAIに質問できるようにします。",
    enableSelfCheckout: "顧客セルフチェックアウトを有効にする",
    enableSelfCheckoutDesc: "お客様が自分の席からセルフチェックアウトで直接注文できるようにします。",
    subAndBilling: "購読と請求管理",
    subDesc: "現在のプラン、決済用クレジットカード、および請求書の履歴を管理します。",
    downloadStatements: "請求明細書のダウンロード",
    currentPlan: "現在のプラン",
    planName: "エンタープライズ・グロース",
    planBilling: "年間契約 • 次回更新日：2026年11月15日",
    activeTerminals: "接続端末数",
    cloudStorage: "クラウド容量",
    changePlan: "プランの変更",
    manageAddons: "アドオン管理",
    paymentMethod: "支払用カード情報",
    editBtn: "編集",
    defaultMethod: "メイン",
    addBackupMethod: "バックアップ用カードの追加",
    invoiceLedger: "請求明细書履歴",
    dateCol: "日付",
    descCol: "内容",
    amountCol: "金額",
    statusCol: "状態",
    actionCol: "操作",
    upcomingStatus: "支払予定",
    paidStatus: "支払済",
    failedStatus: "支払失敗",
    menuWelcome: "メニューエディタ",
    menuDesc: "デジタルメニューやおすすめ料理の追加、編集、削除、およびカテゴリーの管理を行います。",
    avgProfit: "平均利益率",
    totalItems: "メニュー総数",
    specDishes: "おすすめ料理数",
    manageCats: "カテゴリー管理",
    addMenuItem: "メニュー項目を追加",
    editMenuItem: "メニュー項目を編集",
    itemCol: "メニュー項目",
    categoryCol: "カテゴリー",
    costCol: "原価",
    priceCol: "価格",
    marginCol: "利益率",
    actionsCol: "操作",
    categoryManager: "カテゴリー管理",
    addCategory: "カテゴリーを追加",
    editCategory: "カテゴリーを編集",
    categoryName: "カテゴリー名",
    categoryIcon: "アイコン",
    activeCategories: "登録中のカテゴリー",
    hardwareFleet: "周辺機器管理",
    hardwareDesc: "接続されている決済端末、プリンター、キッチンディスプレイ（KDS）、およびキャッシュドロワーの設定を行います。",
    pairNewDevice: "新しい機器をペアリング",
    globalPreferences: "基本接続設定",
    autoReconnect: "デバイスの自動再接続",
    defaultGateway: "デフォルトネットワークゲートウェイ",
    btDiscovery: "Bluetoothビーコンの検出",
    statusIndicators: "デバイスのアラート警告",
    testDrawerKick: "テストドロワー開閉",
    cashDrawers: "キャッシュドロワー設定",
    openOnCash: "現金支払いの完了時に自動でドロワーを開く",
    requireManager: "手動開閉時にマネージャー承認PINコードを要求する",
    staffDirectory: "従業員名簿",
    staffDesc: "スタッフの勤務状況の確認、シフト表の作成、および顧客評価を確認します。",
    onShift: "シフト中",
    offDuty: "勤務外",
    overtime: "残業中",
    weeklyRoster: "週間シフト予定表",
    securityConsole: "セキュリティ設定",
    securityDesc: "役職ごとの操作権限、アクセスログの監視、およびタイムアウト時間を管理します。",
    timeoutLabel: "セッションの有効時間 (分)",
    passcodeLabel: "スタッフ暗証番号の桁数 (桁)",
    roleAccess: "権限管理 (役割ごと)",
    auditTrail: "システム監査アクセスログ",
    taxBasisLabel: "税金計算方法",
    preTaxLabel: "外税 (税抜)",
    postTaxLabel: "内税 (税込)",
    taxBasisDesc: "消費税を小計に追加加算する（外税）か、商品の販売価格に含める（内税）かを選択します。",
    subtotalInclusive: "小計 (税込)",
    includedTax: "内消費税 (8%)",
    analyticsTitle: "ビジネス分析",
    analyticsDesc: "売上・注文・スタッフパフォーマンスとメニューのインサイト。",
    analyticsRange: "期間",
    analyticsToday: "本日",
    analyticsWeek: "今週",
    analyticsMonth: "今月",
    analytics30: "過去30日",
    analyticsRevenue: "総売上",
    analyticsOrders: "総注文数",
    analyticsAvgCheck: "平均客単価",
    analyticsCovers: "来客数",
    analyticsRevTrend: "売上推移",
    analyticsOrderTypes: "注文タイプ別",
    analyticsPeakHours: "ピーク時間帯",
    analyticsTopItems: "売上上位メニュー",
    analyticsStaffPerf: "スタッフ別パフォーマンス",
    analyticsPayMethods: "決済方法の内訳",
    analyticsDineIn: "店内",
    analyticsTakeaway: "テイクアウト",
    analyticsDelivery: "デリバリー",
    analyticsExport: "レポート出力",
    timeBasedMenu: "時間帯別メニュー設定",
    timeBasedMenuDesc: "ランチおよびディナーの提供時間帯を設定します。有効にすると、デジタルメニューの表示内容が現在の時刻に合わせて自動的に切り替わります。",
    lunchMenuTime: "ランチ提供時間帯",
    dinnerMenuTime: "ディナー提供時間帯",
    mealPeriodLabel: "提供時間帯",
    lunchOnly: "ランチのみ",
    dinnerOnly: "ディナーのみ",
    bothMeals: "終日 (両方)",
    timeBasedMenuInfoNote: "提供時間帯が「終日」に指定されているメニューは、すべての時間帯で表示されます。",
    timeBasedMenuDisabledNote: "※時間帯別メニュー設定が無効の場合、提供時間帯の設定に関わらず、すべてのメニュー項目が終日表示されます。",
    inventory: "在庫管理",
    inventoryTitle: "在庫・原材料管理",
    inventoryDesc: "原材料の登録、自動在庫差し引き用のレシピ構成、発注管理、廃棄追跡、および在庫移動ログを管理します。",
  },
  zh: {
    adminConsole: "管理控制台",
    general: "基本设置",
    payments: "收入与账单",
    hardware: "设备管理",
    staff: "员工管理",
    security: "安全设置",
    menu: "菜单编辑",
    analytics: "业务分析",
    activityLog: "操作日志",
    menuEditor: "菜单编辑",
    saveChanges: "保存设置",
    signOut: "退出登录",
    searchPlaceholder: "搜索设置...",
    administrator: "管理员",
    generalTitle: "基本设置",
    generalDesc: "配置餐厅信息、收据模板和界面主题。",
    restaurantInfo: "餐厅信息",
    restaurantName: "餐厅名称",
    contactEmail: "联系邮箱",
    taxIdLabel: "税号 / VAT",
    businessAddress: "营业地址",
    saveProfile: "保存资料",
    globalThemeTitle: "界面主题设置",
    customThemeConfig: "自定义主题配置",
    customThemeDesc: "用您喜欢的颜色定制仪表板",
    diningModes: "用餐模式",
    diningModesDesc: "启用或禁用数字菜单和收银终端中可供顾客选择的用餐选项。",
    displayCurrency: "显示货币",
    taxRatesByDining: "按用餐选项的税率",
    receiptOptionsTitle: "收据与账单布局设置",
    showLogo: "显示店铺标志",
    showLogoDesc: "在收据顶部打印徽标",
    showTaxId: "显示税号",
    showTaxIdDesc: "在收据中包含税号（VAT）",
    showServer: "显示服务员姓名",
    showServerDesc: "在收据上打印收银员姓名",
    showTable: "显示桌号",
    showTableDesc: "显示餐桌编号",
    showTimestamp: "显示订单时间",
    showTimestampDesc: "在收据中包含结账日期时间",
    showFeedbackQr: "显示评价二维码",
    showFeedbackQrDesc: "打印客户评价页面的二维码",
    showSocial: "显示社交媒体链接",
    showSocialDesc: "显示官方社交账号链接",
    includeServiceCharge: "包含服务费",
    includeServiceChargeDesc: "自动添加10%服务费",
    showCustomFooter: "显示自定义页脚",
    showCustomFooterDesc: "在收据底部添加自定义文字",
    livePreview: "实时预览",
    realtimeSync: "同步中",
    currentTable: "餐桌: T-14",
    serverLabel: "服务员: JULIAN B.",
    orderLabel: "订单 #2345",
    subtotal: "小计",
    tax: "税费",
    serviceCharge: "服务费 (10%)",
    gratuity: "小费 (建议20%)",
    grandTotal: "总计",
    regionalSettings: "地区与货币设置",
    languageSelect: "界面语言",
    langEn: "English (US)",
    langJa: "日本語 (Japanese)",
    langZh: "中文（简体）",
    langKo: "한국어 (Korean)",
    digitalMenuPrefs: "数字菜单偏好设置",
    maxDisplayPrice: "最高显示价格",
    maxDisplayPriceDesc: "价格超过此金额的菜品将在顾客菜单中隐藏。",
    excludedFoodTags: "排除的食品标签",
    excludedFoodTagsDesc: "在顾客菜单中隐藏带有这些标签 of 菜品。",
    digitalMenuFeatures: "数字菜单功能开关",
    enableAIConcierge: "启用AI礼宾服务",
    enableAIConciergeDesc: "允许顾客通过AI咨询菜品推荐和搭配建议。",
    enableSelfCheckout: "启用顾客自助结账",
    enableSelfCheckoutDesc: "允许顾客在餐桌上直接自助点单。",
    subAndBilling: "订阅与账单管理",
    subDesc: "管理企业套餐、支付方式和查看即将到期的账单。",
    downloadStatements: "下载账单明细",
    currentPlan: "当前套餐",
    planName: "企业成长版",
    planBilling: "按年计费 • 到期时间：2026年11月15日",
    activeTerminals: "在线终端数",
    cloudStorage: "云存储空间",
    changePlan: "更改套餐",
    manageAddons: "管理附加功能",
    paymentMethod: "支付方式",
    editBtn: "编辑",
    defaultMethod: "默认",
    addBackupMethod: "添加备用支付方式",
    invoiceLedger: "近期账单记录",
    dateCol: "日期",
    descCol: "说明",
    amountCol: "金额",
    statusCol: "状态",
    actionCol: "操作",
    upcomingStatus: "待付款",
    paidStatus: "已付款",
    failedStatus: "付款失败",
    menuWelcome: "菜单编辑器",
    menuDesc: "创建、编辑、分类和管理餐厅数字菜单。",
    avgProfit: "平均利润率",
    totalItems: "菜品总数",
    specDishes: "特色菜品",
    manageCats: "管理分类",
    addMenuItem: "添加菜品",
    editMenuItem: "编辑菜品",
    itemCol: "菜品",
    categoryCol: "分类",
    costCol: "成本",
    priceCol: "售价",
    marginCol: "利润率",
    actionsCol: "操作",
    categoryManager: "分类管理",
    addCategory: "添加分类",
    editCategory: "编辑分类",
    categoryName: "分类名称",
    categoryIcon: "分类图标",
    activeCategories: "已启用分类",
    hardwareFleet: "硬件设备",
    hardwareDesc: "监控连接的终端设备、打印机、展示屏及收银抽屉。",
    pairNewDevice: "配对新设备",
    globalPreferences: "全局偏好设置",
    autoReconnect: "自动重新连接设备",
    defaultGateway: "默认网关",
    btDiscovery: "蓝牙信标发现",
    statusIndicators: "状态告警",
    testDrawerKick: "测试收银抽屉",
    cashDrawers: "收银抽屉",
    openOnCash: "现金结账时自动打开",
    requireManager: "手动开启需要管理员PIN授权",
    staffDirectory: "员工目录",
    staffDesc: "监控员工状态、排班情况和客户满意度评分。",
    onShift: "在班",
    offDuty: "休息",
    overtime: "加班",
    weeklyRoster: "每周排班表",
    securityConsole: "安全控制台",
    securityDesc: "修改权限控制、查看系统审计记录及设置会话超时。",
    timeoutLabel: "会话空闲超时（分钟）",
    passcodeLabel: "默认员工密码长度（位数）",
    roleAccess: "角色访问权限",
    auditTrail: "系统审计日志",
    taxBasisLabel: "税金计算方式",
    preTaxLabel: "税前（不含税）",
    postTaxLabel: "税后（含税）",
    taxBasisDesc: "选择税金是在小计之外加收（税前）还是已包含在价格中（税后）。",
    subtotalInclusive: "小计（含税）",
    includedTax: "含税额 (8%)",
    analyticsTitle: "业务分析",
    analyticsDesc: "餐厅的收入、订单、员工绩效和菜单洞察。",
    analyticsRange: "日期范围",
    analyticsToday: "今天",
    analyticsWeek: "本周",
    analyticsMonth: "本月",
    analytics30: "过去30天",
    analyticsRevenue: "总收入",
    analyticsOrders: "总订单数",
    analyticsAvgCheck: "平均消费",
    analyticsCovers: "接待人数",
    analyticsRevTrend: "收入趋势",
    analyticsOrderTypes: "订单类型",
    analyticsPeakHours: "高峰时段分布",
    analyticsTopItems: "热销菜品",
    analyticsStaffPerf: "员工绩效",
    analyticsPayMethods: "支付方式分布",
    analyticsDineIn: "堂食",
    analyticsTakeaway: "外带",
    analyticsDelivery: "外卖",
    analyticsExport: "导出报告",
    timeBasedMenu: "分时段菜单设置",
    timeBasedMenuDesc: "启用午餐和晚餐菜单服务时段。启用后，顾客数字菜单将根据当前本地时间动态过滤菜单项。",
    lunchMenuTime: "午餐服务时间",
    dinnerMenuTime: "晚餐服务时间",
    mealPeriodLabel: "适用时段",
    lunchOnly: "仅限午餐",
    dinnerOnly: "仅限晚餐",
    bothMeals: "全天（两者皆可）",
    timeBasedMenuInfoNote: "提供时段为“全天”的菜品将在所有服务时段显示。",
    timeBasedMenuDisabledNote: "注：分时段菜单关闭时，所有菜单项将全天显示，不受适用时段设置的影响。",
    inventory: "库存管理",
    inventoryTitle: "库存与配方管理",
    inventoryDesc: "配置原料、关联菜单项以实现自动扣减、管理供应商、采购订单以及跟踪损耗记录。",
  },
  ko: {
    adminConsole: "관리 콘솔",
    general: "일반 설정",
    payments: "매출 및 청구",
    hardware: "하드웨어 설정",
    staff: "직원 관리",
    security: "보안 설정",
    menu: "메뉴 편집",
    analytics: "비즈니스 분석",
    activityLog: "활동 로그",
    menuEditor: "메뉴 편집",
    saveChanges: "설정 저장",
    signOut: "로그아웃",
    searchPlaceholder: "설정 검색...",
    administrator: "관리자",
    generalTitle: "일반 설정",
    generalDesc: "레스토랑 정보, 영수증 템플릿 및 화면 테마를 구성합니다.",
    restaurantInfo: "레스토랑 정보",
    restaurantName: "레스토랑 이름",
    contactEmail: "연락처 이메일",
    taxIdLabel: "사업자 번호 / VAT",
    businessAddress: "사업장 주소",
    saveProfile: "정보 저장",
    globalThemeTitle: "테마 설정",
    customThemeConfig: "커스텀 테마 구성",
    customThemeDesc: "원하는 색상으로 대시보드를 커스터마이즈하세요",
    diningModes: "다이닝 모드",
    diningModesDesc: "디지털 메뉴와 계산대에서 고객이 이용할 수 있는 식사 옵션을 활성화/비활성화합니다.",
    displayCurrency: "표시 통화",
    taxRatesByDining: "식사 옵션별 세율",
    receiptOptionsTitle: "영수증 및 청구서 레이아웃 설정",
    showLogo: "매장 로고 표시",
    showLogoDesc: "영수증 상단에 로고를 인쇄합니다",
    showTaxId: "사업자 번호 표시",
    showTaxIdDesc: "영수증에 사업자 번호(VAT)를 포함합니다",
    showServer: "담당 직원 이름 표시",
    showServerDesc: "영수증에 계산원 이름을 인쇄합니다",
    showTable: "테이블 번호 표시",
    showTableDesc: "테이블 ID를 표시합니다",
    showTimestamp: "주문 일시 표시",
    showTimestampDesc: "영수증에 결제 날짜와 시간을 포함합니다",
    showFeedbackQr: "고객 평가 QR 표시",
    showFeedbackQrDesc: "고객 평가 페이지의 QR 코드를 인쇄합니다",
    showSocial: "SNS 링크 표시",
    showSocialDesc: "공식 SNS 계정 링크를 표시합니다",
    includeServiceCharge: "서비스 요금 포함",
    includeServiceChargeDesc: "자동으로 10% 서비스 요금을 추가합니다",
    showCustomFooter: "사용자 지정 푸터 메시지 표시",
    showCustomFooterDesc: "영수증 하단에 사용자 지정 텍스트를 추가합니다",
    livePreview: "실시간 미리보기",
    realtimeSync: "동기화 중",
    currentTable: "테이블: T-14",
    serverLabel: "담당: JULIAN B.",
    orderLabel: "주문 #2345",
    subtotal: "소계",
    tax: "세금",
    serviceCharge: "서비스 요금 (10%)",
    gratuity: "팁 (권장 20%)",
    grandTotal: "합계",
    regionalSettings: "지역 및 통화 설정",
    languageSelect: "대시보드 언어",
    langEn: "English (US)",
    langJa: "日本語 (Japanese)",
    langZh: "中文（简体）",
    langKo: "한국어 (Korean)",
    digitalMenuPrefs: "디지털 메뉴 환경설정",
    maxDisplayPrice: "최대 표시 가격",
    maxDisplayPriceDesc: "이 금액을 초과하는 메뉴 항목은 고객용 메뉴에서 숨겨집니다.",
    excludedFoodTags: "제외할 음식 태그",
    excludedFoodTagsDesc: "이 태그가 포함된 메뉴 항목을 고객 메뉴에서 숨깁니다.",
    digitalMenuFeatures: "디지털 메뉴 기능 설정",
    enableAIConcierge: "AI 컨시어지 활성화",
    enableAIConciergeDesc: "고객이 AI에게 메뉴 추천 및 페어링에 대해 질문할 수 있도록 합니다.",
    enableSelfCheckout: "고객 셀프 체크아웃 활성화",
    enableSelfCheckoutDesc: "고객이 테이블에서 직접 셀프 체크아웃으로 주문할 수 있도록 합니다.",
    subAndBilling: "구독 및 청구 관리",
    subDesc: "현재 플랜, 결제 방법 및 청구서 내역을 관리합니다.",
    downloadStatements: "청구서 명세서 다운로드",
    currentPlan: "현재 플랜",
    planName: "엔터프라이즈 성장 플랜",
    planBilling: "연간 결제 • 갱신일: 2026년 11월 15일",
    activeTerminals: "활성 단말기",
    cloudStorage: "클라우드 저장소",
    changePlan: "플랜 변경",
    manageAddons: "부가 기능 관리",
    paymentMethod: "결제 방법",
    editBtn: "편집",
    defaultMethod: "기본",
    addBackupMethod: "백업 결제 방법 추가",
    invoiceLedger: "청구서 내역",
    dateCol: "날짜",
    descCol: "설명",
    amountCol: "금액",
    statusCol: "상태",
    actionCol: "작업",
    upcomingStatus: "예정",
    paidStatus: "결제 완료",
    failedStatus: "결제 실패",
    menuWelcome: "메뉴 편집기",
    menuDesc: "디지털 메뉴 항목을 생성, 편집, 분류 및 관리합니다.",
    avgProfit: "평균 이익률",
    totalItems: "전체 메뉴 수",
    specDishes: "특선 요리",
    manageCats: "카테고리 관리",
    addMenuItem: "메뉴 항목 추가",
    editMenuItem: "메뉴 항목 편집",
    itemCol: "메뉴 항목",
    categoryCol: "카테고리",
    costCol: "원가",
    priceCol: "판매가",
    marginCol: "마진",
    actionsCol: "작업",
    categoryManager: "카테고리 관리자",
    addCategory: "카테고리 추가",
    editCategory: "카테고리 편집",
    categoryName: "카테고리 이름",
    categoryIcon: "카테고리 아이콘",
    activeCategories: "활성 카테고리",
    hardwareFleet: "하드웨어 기기",
    hardwareDesc: "연결된 단말기, 프린터, 전시 화면 및 계산기 서랍을 모니터링합니다.",
    pairNewDevice: "새 기기 페어링",
    globalPreferences: "전역 환경설정",
    autoReconnect: "기기 자동 재연결",
    defaultGateway: "기본 네트워크 게이트웨이",
    btDiscovery: "블루투스 비콘 검색",
    statusIndicators: "상태 알림",
    testDrawerKick: "계산기 서랍 테스트",
    cashDrawers: "계산기 서랍",
    openOnCash: "현금 결제 시 자동 열기",
    requireManager: "수동 개방 시 관리자 PIN 인증 필요",
    staffDirectory: "직원 목록",
    staffDesc: "직원 상태, 교대 일정 및 고객 만족도를 모니터링합니다.",
    onShift: "근무 중",
    offDuty: "휴무",
    overtime: "초과 근무",
    weeklyRoster: "주간 근무 일정",
    securityConsole: "보안 콘솔",
    securityDesc: "역할 접근 권한 수정, 시스템 감사 기록 검토 및 세션 타임아웃 설정.",
    timeoutLabel: "세션 유휴 타임아웃 (분)",
    passcodeLabel: "기본 직원 비밀번호 길이 (자리)",
    roleAccess: "역할별 접근 권한",
    auditTrail: "시스템 감사 로그",
    taxBasisLabel: "세금 계산 방식",
    preTaxLabel: "세전 (외세)",
    postTaxLabel: "세후 (내세)",
    taxBasisDesc: "세금을 소계에 추가 적용할지(세전) 가격에 포함할지(세후) 선택합니다.",
    subtotalInclusive: "소계 (세금 포함)",
    includedTax: "포함 세금 (8%)",
    analyticsTitle: "비즈니스 분석",
    analyticsDesc: "매출, 주문, 직원 성과 및 메뉴 인사이트.",
    analyticsRange: "기간",
    analyticsToday: "오늘",
    analyticsWeek: "이번 주",
    analyticsMonth: "이번 달",
    analytics30: "최근 30일",
    analyticsRevenue: "총 매출",
    analyticsOrders: "총 주문 수",
    analyticsAvgCheck: "평균 결제액",
    analyticsCovers: "방문 고객 수",
    analyticsRevTrend: "매출 추이",
    analyticsOrderTypes: "주문 유형별",
    analyticsPeakHours: "피크 시간대",
    analyticsTopItems: "인기 메뉴",
    analyticsStaffPerf: "직원별 성과",
    analyticsPayMethods: "결제 수단 현황",
    analyticsDineIn: "매장",
    analyticsTakeaway: "포장",
    analyticsDelivery: "배달",
    analyticsExport: "보고서 내보내기",
    timeBasedMenu: "시간대별 메뉴 설정",
    timeBasedMenuDesc: "점심 및 저녁 메뉴 서비스 시간대를 설정합니다. 활성화하면 고객용 디지털 메뉴가 현재 현지 시간에 따라 메뉴 항목을 동적으로 필터링합니다.",
    lunchMenuTime: "점심 서비스 시간",
    dinnerMenuTime: "저녁 서비스 시간",
    mealPeriodLabel: "제공 시간대",
    lunchOnly: "점심 전용",
    dinnerOnly: "저녁 전용",
    bothMeals: "종일 (모두)",
    timeBasedMenuInfoNote: "제공 시간대가 '종일'로 설정된 메뉴는 모든 시간대에 표시됩니다.",
    timeBasedMenuDisabledNote: "참고: 시간대별 메뉴 설정이 비활성화된 경우, 지정된 시간대와 관계없이 모든 메뉴 항목이 종일 표시됩니다.",
    inventory: "재고 관리",
    inventoryTitle: "재고 및 레시피 관리",
    inventoryDesc: "원재료 설정, 자동 재고 차감을 위한 메뉴 레시피 연동, 공급업체 관리, 발주 및 폐기 기록을 관리합니다.",
  }
};
